COMP: Use BSplineTransform instead of deprecated BSplineTransformInitializer
See "B-spline Registration Refactoring" migration guide
available at https://itk.org/migrationv4/index.php?action=artikel&cat=3&id=82&artlang=en
and also documentation associated with itk::BSplineTransform::SetFixedParameters()
at https://itk.org/Insight/Doxygen/html/classitk_1_1BSplineTransform.html#aff697faefc33b586c4560114226bc499

Note that call to "GetGridRegion()" was replaced with call
to "GetTransformDomainMeshSize()".


This commit fixes build errors like the following when building against
ITK without ITKV3Compatibility module:

```
/tmp/DTIPrep/src/itkMultiImageRegistrationFilter.h:242:11: error: ‘BSplineDeformableTransformInitializer’ does not name a type
   typedef BSplineDeformableTransformInitializer<BSplineTransformType, ImageType> BSplineInitializerType;
           ^
/tmp/DTIPrep/src/itkMultiImageRegistrationFilter.h:330:15: error: ‘BSplineInitializerType’ was not declared in this scope
   std::vector<BSplineInitializerType::Pointer> m_BsplineInitializerArray;
               ^
/tmp/DTIPrep/src/itkMultiImageRegistrationFilter.h:330:46: error: template argument 1 is invalid
   std::vector<BSplineInitializerType::Pointer> m_BsplineInitializerArray;
                                              ^
/tmp/DTIPrep/src/itkMultiImageRegistrationFilter.h:330:46: error: template argument 2 is invalid
In file included from /tmp/DTIPrep/src/GMainWindow.h:6:0,
                 from /tmp/DTIPrep/src/main.cxx:11:

```