COMP: LinearHeadEddy3DCorrection: Use "GetMatrix" instead of deprecated "GetRotationMatrix"
This commit fixes the build errors like the following when building against
ITK without ITKV3Compatibility module:

```
/tmp/DTIPrep/src/itkLinearHeadEddy3DCorrection.hxx: In member function ‘const RotationMatrixType& itk::LinearHeadEddy3DCorrection<TScalarType, NInputDimensions, NOutputDimensions>::GetHeadMotionRotationMatrix() const’:
/tmp/DTIPrep/src/itkLinearHeadEddy3DCorrection.hxx:174:35: error: ‘itk::SmartPointer<itk::VersorRigid3DTransform<double> >::ObjectType {aka struct itk::VersorRigid3DTransform<double>}’ has no member named ‘GetRotationMatrix’
   return m_head_motion_transform->GetRotationMatrix();
                                   ^
```